// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9OFDed-Ikhtp0_mnsUTR1OuNgUZ7ZJE',
    appId: '1:156349816591:web:3de2d2762f0cfe8645a87a',
    messagingSenderId: '156349816591',
    projectId: 'my-wonderful-project-999',
    authDomain: 'my-wonderful-project-999.firebaseapp.com',
    storageBucket: 'my-wonderful-project-999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-8BOXUqK4gHqEYd_clDsX0uZaitaFByA',
    appId: '1:156349816591:android:a39bfdade2b8483f45a87a',
    messagingSenderId: '156349816591',
    projectId: 'my-wonderful-project-999',
    storageBucket: 'my-wonderful-project-999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBytf2D1GtWDjrvOwa1Ez29t90ionP5nUE',
    appId: '1:156349816591:ios:32cd6abd110db26e45a87a',
    messagingSenderId: '156349816591',
    projectId: 'my-wonderful-project-999',
    storageBucket: 'my-wonderful-project-999.firebasestorage.app',
    iosBundleId: 'com.example.carRentalAppTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBytf2D1GtWDjrvOwa1Ez29t90ionP5nUE',
    appId: '1:156349816591:ios:32cd6abd110db26e45a87a',
    messagingSenderId: '156349816591',
    projectId: 'my-wonderful-project-999',
    storageBucket: 'my-wonderful-project-999.firebasestorage.app',
    iosBundleId: 'com.example.carRentalAppTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj9OFDed-Ikhtp0_mnsUTR1OuNgUZ7ZJE',
    appId: '1:156349816591:web:0a5d6ef96b17274745a87a',
    messagingSenderId: '156349816591',
    projectId: 'my-wonderful-project-999',
    authDomain: 'my-wonderful-project-999.firebaseapp.com',
    storageBucket: 'my-wonderful-project-999.firebasestorage.app',
  );

}